name: arca_connect_sdk
description: SDK para integrar factura electrónica ARCA (ex AFIP) en Flutter/Dart. Emití facturas A, B, C con CAE.
version: 0.1.0
license: MIT
homepage: https://arcaconnect.com
repository: https://github.com/tusistemaamedida/arca-connect-sdk-dart
issue_tracker: https://github.com/tusistemaamedida/arca-connect-sdk-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  freezed_annotation: ^2.4.0
  json_annotation: ^4.9.0

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  lints: ^3.0.0
